name: automerge
on:
  workflow_run:
    workflows: [Sync master into other branch]
    types: [completed]
    branches: [master]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: 'pascalgn/automerge-action@v0.15.3'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_LABELS: ''
