name: Automerge testing 3
on:
  workflow_run:
    workflows: [Automerge testing 2]
    types: [completed]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: 'pascalgn/automerge-action@v0.15.3'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
