name: Prettier Action

# This action works with pull requests and pushes
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  prettier_action:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Prettier Check
        uses: creyD/prettier_action@v4.2
        with:
          dry: True
          prettier_options: --check **/*.{js,md}
